Шишебаров Александр test-api-gateway
velp/test-api-gateway pull request #7
Opened 2021-01-06 10:34 UTC by mythvcode

Задание выполнил. Описание решения в README. 
Описание задания и примеры запросов в docs.

2021-01-06 12:18 UTC, velp requested changes
Интересная идея не плодить хендлеры API а делать поиск функции из листа и вызывать ее, но такой подход заставил тебя переносить логику API в модули и функции которые работают с OpenStack API а также делать неявные проверки передаваемых параметров в функции и возвращать исключения `BadRequest` из этих функций. С точки зрения подхода MVC и принятой логики разделения стоит делать все проверки входных данных в самих хендлерах API.

В модулях которые работают с OpenStack API стоит использовать классы, чтобы исключить ненужное переинициализированние клиентов и лишнее выделение памяти.

Кое-где встречается хардкод и недостаточное количество гибкости через ENV переменные.

Есть еще несколько вопросов на подумать:
1. как будет работать API если в системе 2000 созданных виртуальных машин?
2. что будет происходить если придет брутфорс атака на перебор юзера/пароля в API?

2021-01-06 12:18 UTC, velp commented on wsgi.py
> +        return make_response(jsonify({"msg": f"Error create server {excp}"}), 400)
Очень много где в этом файл у тебя есть код вида `make_response(jsonify({"msg": ...`. Возможно стоит вынести его в отдельную функцию чтобы уменьшить дубликат.

2021-01-07 18:15 UTC, mythvcode commented on appmods/opensnet.py
> +        tmp = neutron.list_subnets(id=netid)["subnets"][0]
Если список пуст, то в цикле не будет итераций, думаю что проверка на пустой список не даст никакого ускорения.

2021-01-07 18:17 UTC, mythvcode commented on appmods/opensnet.py
> +                       'subnets': _get_subnets(net["subnets"], neutron)})
Согласен класс напрашивается поправлю.

2021-01-07 18:17 UTC, mythvcode commented on appmods/opensserver.py
> +    nova = client.Client(version='2', session=sess)
Доделаю.

2021-01-07 18:19 UTC, mythvcode commented on appmods/opensserver.py
> +        tmp = [fl for fl in nova.flavors.list()
Не похожа сигнатура вызова list. у других в ней передается id.
Поправлю.

2021-01-07 18:21 UTC, mythvcode commented on appmods/opensserver.py
> +        raise  BadRequest(f"Not allowed action {data['action']}") from KeyError
Здесь ругался pylint. Требовал чтобы сделал так.

2021-01-07 18:31 UTC, mythvcode commented on wsgi.py
> +        auth = loader.load_from_options(auth_url=f"http://{KEYSTONE_HOST}/identity",
Согласен, доделаю.

2021-01-07 18:31 UTC, mythvcode commented on wsgi.py
> +    catches the Unauthorized, DiscoveryFailure, ConnectFailure  exceptions from the called function.
Странно pylint не ругался.

2021-01-07 18:32 UTC, mythvcode commented on wsgi.py
> +logging.basicConfig(filename="/var/log/api-gateway/api.log", level=logging.INFO)
Gunicorn создает автоматически.
Но думаю стоит создавать если нет директории, в конфигурации gunicorn можно изменить директорию хранения.

2021-01-07 18:39 UTC, velp commented on appmods/opensnet.py
> +        tmp = neutron.list_subnets(id=netid)["subnets"][0]
Речь про конкретно 21 строку, если `neutron.list_subnets(id=netid)["subnets"]` - это пустой лист, а у тебя попытка сразу получить первый элемент

2021-01-07 18:42 UTC, velp commented on appmods/opensserver.py
> +        raise  BadRequest(f"Not allowed action {data['action']}") from KeyError
Хм, а как выглядела ошибка? Можешь скинуть?

2021-01-07 18:53 UTC, mythvcode commented on appmods/opensnet.py
> +        tmp = neutron.list_subnets(id=netid)["subnets"][0]
Точно.
Поправлю.

2021-01-07 18:59 UTC, mythvcode commented on appmods/opensserver.py
> +        raise  BadRequest(f"Not allowed action {data['action']}") from KeyError
opensserver.py:134:8: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)

2021-01-07 19:57 UTC, mythvcode commented on wsgi.py
> +        return make_response(jsonify({"msg": f"Error create server {excp}"}), 400)
Согласен, можно написать функцию например make_err_response(excp) отлавливать nova ClientException, keystone ClientException.
Передавать их в функцию и в зависимости от ошибки формировать ответ.
Проверять тип ошибки все равно придется, так-как код возврата и текст отличаются в зависимости от типа Exception.

2021-01-08 09:32 UTC, velp commented on wsgi.py
> +logging.basicConfig(filename="/var/log/api-gateway/api.log", level=logging.INFO)
Тут скорее речь про захардкоженный путь в коде, и что его может понадобиться изменить, или запустить без gunicorn.

2021-01-08 13:56 UTC, mythvcode commented on wsgi.py
> +                                        user_domain_id="default")
Так сделано по большему счету для простоты.
Ситуация когда нужно будет создать другого пользователя в другом домене возникнуть может.
Возникает вопрос как определить домен, так как в разных доменах может быть пользователь с одинаковым username.
Но для аутентификации всегда нужен user_domain_id, или user_domain_name(по крайне мере я не нашел как пройти аутентификацию без него в v3 identity), и здесь возникает вопрос как определить домен, так как в разных доменах может быть пользователь с одинаковым username. 
И если мы не можем определить домен возникает вопрос как его передать в http basic auth(тоже была выбрана для простоты) в принципе можно как-то так curl -u <user>-<domain>:<password>

2021-01-08 15:37 UTC, mythvcode commented on appmods/opensserver.py
> +    reuired_data = ("server_name", "image_id", "flavor_id", "network_ids")
Дополнительной логики нет, так просто легко сформировать список того что было передано в data

2021-01-09 07:56 UTC, velp commented on wsgi.py
> +                                        user_domain_id="default")
По идеи, если ты хочешь для своего API так же использовать keystone аутентификацию, то все данные для нее надо передавать в виде JSON тела а не через basic auth. Тогда у тебя будет возможность передать что угодно и как угодно.
Домен должен либо передаваться в теле авторизации (как описано выше), либо, быть частью настроек сервиса, то есть передаваться через ENV переменную.

2021-01-09 08:00 UTC, velp commented on appmods/opensserver.py
> +    reuired_data = ("server_name", "image_id", "flavor_id", "network_ids")
Это довольно не явное представление функции. То есть мне как разработчику который будет править этот код, надо будет обязательно лезть в эту функцию и проверять что и как должно передаваться, хотя эту роль должно выполнять doc strings и параметры функции.
Ну и смешение view/controller частей API.

2021-01-09 18:13 UTC, mythvcode commented on wsgi.py
> +                                        user_domain_id="default")
Можно передавать в json, только  в случае с get запросом передавать в теле запроса json вроде как плохой тон, у меня просили php программисты просили  переделать передачу из json  в get переменные, так как они в своих библиотеках не могли в get запросе передавать json.
Изначально планировал сделать аутентификацию через токены, отдельным методом его получать.
В этом же случае можно было бы организовать защиту от брутфорса, и не передавать пароль в каждом запросе.

2021-01-10 18:03 UTC, velp commented on wsgi.py
> +        return make_response(jsonify({"msg": f"Error create server {excp}"}), 400)
Обычно для авторизации делается отдельный эндпоинт в который POST улетает все что надо для проверки, в ответ возвращется токен. Следующий запрос (GET нужный) уже идет с этим токеном. Если ты делаешь авторизацию в кейстоун то ты можешь прям туда прокидывать все данные из json POST и оттуда же брать токен. И так же валидировать токен через keystone. Чтобы не городить свой код с JWT токенами или какими-то другими токенами.

2021-01-10 18:03 UTC, velp commented on wsgi.py
> +                                        user_domain_id="default")
Обычно для авторизации делается отдельный эндпоинт в который POST улетает все что надо для проверки, в ответ возвращется токен. Следующий запрос (GET нужный) уже идет с этим токеном. Если ты делаешь авторизацию в кейстоун то ты можешь прям туда прокидывать все данные из json POST и оттуда же брать токен. И так же валидировать токен через keystone. Чтобы не городить свой код с JWT токенами или какими-то другими токенами.

2021-01-10 18:05 UTC, velp commented on wsgi.py
> +    WSGI_LOG = "/var/log/api-gateway/api.log"
можно сделать все в одну строку: `WSGI_LOG = os.environ.get("WSGI_LOG", "/var/log/api-gateway/api.log")`

2021-01-10 18:05 UTC, velp commented on wsgi.py
> +    USER_DOMAIN_ID = "default"
аналогично

2021-01-10 18:50 UTC, mythvcode commented on wsgi.py
> +                                        user_domain_id="default")
Так и планировал. Просто на первых парах показалось проще делать через basic auth.
Напишу в общем комменте.

2021-01-10 19:05 UTC, mythvcode commented
Вроде пока все замечания по коду исправил.
Перенес логику проверки входящих данных в хандлеры.
По поводу доп. вопросов.
 1. Как будет работать API если в системе 2000 созданных виртуальных машин?
     Видимо речь идет об объёме передаваемых данных в случае запроса на список серверов.
     Здесь можно снизить нагрузку используя  ```limit servers.list(limit=10)```, и переписывать его переменной из get запроса 
     если она есть.
     Так же можно сделать поиск c использованием search_opts ```servers.list(search_opts={"name1":"servername*"})```
     Еще, вероятно, можно разделить созданные серверы на проекты, и передавать данные только одного проекта.
2. Что будет происходить если придет брутфорс атака на перебор юзера/пароля в API?
    В принципе с эмулировал перебор 1000 одновременных запросов, keystoneuWSGI задумался но переварил.
    Можно сделать следующее сделать отдельный endpoint в котором сделать аутентификацию, результатом успешной 
    аутентификации будет получение токена(Можно борть токен из объекта Session, он выдается krystone на час и дальше 
    использовать его).
    В качестве защиты от перебора можно ограничить количество попыток например с одного ip используя flask_limiter.
    Или есть способ попроще?

2021-01-11 14:32 UTC, velp commented
1. Вопрос был в сторону пагинации и таймаутов, limit в запросе решает только первую проблему.
2. Тут нужен комплекс решений: отдельный эндпоинт авторизации, токены а не валидация юзер/пароль с походом в базу каждый раз, кэш. Всякие блокировки на стороне API бесполезны, во-первых есть NAT, во-вторых скорее всего ресурсы API начнут тратиться на это вместо обработки нормальных запросов. Защита такого плана должна быть уже до API, на самом API перечисленные раньше методы просто повысят "живучесть" API.

2021-01-11 14:33 UTC, velp approved these changes

2021-01-11 14:33 UTC, merged